spring.application.name=Messenger

spring.datasource.url=jdbc:h2:mem:messengerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
